// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmtrkpbcfzjjakavndgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptdHJrcGJjZnpqamFrYXZuZGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDkxNDksImV4cCI6MjA1ODYyNTE0OX0.50wZQdj1xBfV9mEyDsWcQ2uxH6U38Yl3tOqcPTJmUJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);